name: Run Email Script Weekdays

on:
  schedule:
    - cron: '0 8 * * 1-5'   # 8:00 AM UTC, Mon–Fri
  workflow_dispatch:        # (optional) manual trigger

jobs:
  run-email-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SENT_RECIPIENTS_EMAIL_LISTS : ${{ secrets.SENT_RECIPIENTS_EMAIL_LISTS }}

        run: |
          python whom_received_emails_from_me.py
